Themeing color
prixite/trail-frontend pull request #10
Opened 2022-06-16 07:07 UTC by faisalusmanprixite

2022-06-16 08:05 UTC, getalihassan requested changes

2022-06-16 08:05 UTC, getalihassan commented on src/components/common/Presentational/TrailList/TrailList.tsx
> +    TrailsDataService.getAll()
please avoid chainning method, convert it into promise style with async/await. and avoid this approach as I have told you many times

2022-06-16 08:16 UTC, getalihassan requested changes

2022-06-16 11:01 UTC, getalihassan requested changes

2022-06-16 11:01 UTC, getalihassan commented on src/services/TrailsService.ts
> +import http from 'src/http-common';
this file will get refactored please connect with Abdullah

2022-06-16 11:03 UTC, getalihassan commented
@faisalusmanprixite change the name of branch and name of PR

2022-06-20 06:32 UTC, getalihassan requested changes

2022-06-20 06:32 UTC, getalihassan commented on package.json
> +    "axios": "^0.27.2",
remove this as we are not using axsio now

2022-06-20 06:32 UTC, getalihassan commented on src/components/common/Presentational/TrailList/TrailList.tsx
> +  console.log('traildata', trails);
remove console

2022-06-20 06:33 UTC, faisalusmanprixite commented on package.json
> +    "axios": "^0.27.2",
ok

2022-06-20 06:34 UTC, faisalusmanprixite commented on src/components/common/Presentational/TrailList/TrailList.tsx
> +  console.log('traildata', trails);
ok

2022-06-20 06:40 UTC, merged